### ISSUE TITLE
`/storageusage` sometimes returns different value

### ISSUE THREAD

**Issue by gaishimo** [orangesys/orangeapi#1]
通常は
`{"storageUsage":73550242}`
ですが、たまに 1/2の値が返ってくることがある。
`{"storageUsage":36775121}`

**Comment by gavinzhou** [comment]
SQLタイミングの問題、すぐ解決難しい
( ◠‿◠ )

**Comment by gaishimo** [comment]
DBは実際に、一時的にこの値になっているということなんですね 👀

**Comment by gavinzhou** [comment]
sqlの方で直した
@gaishimo
